language: erlang
otp_release:
  - 17.0
env:
  - CPATH=/usr/lib/llvm-3.4/include LIBRARY_PATH=/usr/lib/llvm-3.4/lib LD_LIBRARY_PATH=/usr/lib/llvm-3.4/lib
before_install:
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update
  - sudo apt-get install libclang1-3.4 libclang-3.4-dev
  - dialyzer --build_plt --apps erts kernel stdlib compiler
script: "make all"

